require('user.config.autocmds.buffers')
require('user.config.autocmds.windows')
require('user.config.autocmds.macro')
require('user.config.autocmds.terminal')
require('user.config.autocmds.listchars')
