# Interface
style = "compact"
inline_height = 10
show_help = false
show_tabs = false
show_preview = false

# Search & Filter
workspaces = true
filter_mode_shell_up_key_binding = "session"

# Behavior
enter_accept = false
keymap_mode = "vim-insert"
