#!/usr/bin/env bash

export PATH="/usr/local/bin:$PATH"

declare gitdir="$(git rev-parse --git-dir)"

git ls-files \
	| ctags \
		-L - \
		-f "$gitdir/$$.tags" \
		--tag-relative=yes \
		--languages=-javascript,sql

mv "$gitdir/$$.tags" "$gitdir/tags"
