#!/usr/bin/env node

/*
 * push - Send notification to Pushbullet
 *
 * SYNOPSIS
 *   $ push <message>
 *
 * @author Kutsan Kaplan <me@kutsankaplan.com>
 * @license GPLv3
 * @version v0.1.0
 */

if (process.argv.includes('--help') || process.argv.includes('-h')) {
	console.log(`
  Send notification to Pushbullet

  SYNOPSIS
    $ push <message>

  AUTHOR
    Kutsan Kaplan <me@kutsankaplan.com>
`)
	process.exit(0)
}

const fs = require('fs')
const os = require('os')
const https = require('https')

const showError = (message) => console.error(`\n  \x1b[41;37m error \x1b[0m ${message}\n`)

let PUSHBULLET_API_KEY

try {
	PUSHBULLET_API_KEY = fs.readFileSync(`${os.homedir()}/.config/push/config`, 'UTF-8').trim()
} catch (err) {
	showError('You need to create ~/.config/push/config file with your "Pushbullet Access Token".')
	process.exit(1)
}

const postData = {
	type: 'note',
	title: process.argv.slice(2).join(' ') || 'Signal sent by `push`'
}

const req = https.request(
	{
		method: 'POST',
		hostname: 'api.pushbullet.com',
		path: '/v2/pushes',
		headers: {
			'Access-Token': PUSHBULLET_API_KEY,
			'Content-Type': 'application/json'
		}
	},
	(res) => {
		if (res.statusCode !== 200)
			showError(res.statusCode, '/', res.statusMessage)
})

req.on('error', (err) => {
	showError(err.message)
})

req.write(JSON.stringify(postData))
req.end()
