# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  scrollHeight: 10
  expandFocusedSidePanel: true
  enlargedSideViewLocation: 'top'
  theme:
    activeBorderColor:
      - blue
    inactiveBorderColor:
      - black
    searchingActiveBorderColor:
      - cyan
    optionsTextColor:
      - black
    selectedLineBgColor:
      - black
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    markedBaseCommitFgColor:
      - blue
    markedBaseCommitBgColor:
      - yellow
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
  showCommandLog: false
  showBottomLine: false
  nerdFontsVersion: '3'
  spinner:
    frames:
      - '⠦'
      - '⠖'
      - '⠲'
      - '⠴'
    rate: 100
  statusPanelView: allBranchesLog

git:
  pagers:
    - pager: delta --paging=never
      colorArg: always
  branchLogCmd: 'git l --color=always --remotes {{branchName}} --'
  allBranchesLogCmds:
    - 'git la --color=always'

os:
  editPreset: 'nvim'

customCommands:
  - key: 'R'
    command: 'gh repo view --web'
    description: 'View repository on GitHub'
    context: 'global'
    loadingText: 'Opening GitHub...'

  - key: 'o'
    command: 'gh pr view --web {{ .SelectedLocalBranch.Name }}'
    description: 'View PR on GitHub'
    context: 'localBranches, remoteBranches'
    loadingText: 'Opening GitHub...'

notARepository: 'quit'

promptToReturnFromSubprocess: false
