# yaml-language-server: $schema=https://json.schemastore.org/lazydocker.json

gui:
  theme:
    activeBorderColor:
      - blue
    inactiveBorderColor:
      - black
    selectedLineBgColor:
      - black
    optionsTextColor:
      - black
  returnImmediately: true
  showBottomLine: false
  expandFocusedSidePanel: true
  containerStatusHealthStyle: "icon"
