#!/usr/bin/env bash
# shellcheck disable=SC1091

set -o errexit -o nounset -o pipefail
IFS=$'\n\t'

config_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly config_dir

(source "$config_dir/options/main.sh")
(source "$config_dir/sections/main.sh")
