background = #f5f5f5
foreground = #31363f

cursor-color = #384d71
cursor-text = #f5f5f5
selection-background = #d7d9dd
selection-foreground = #31363f
split-divider-color = #dddfe3

palette = 0=#3d424d
palette = 1=#8d4c57
palette = 2=#386955
palette = 3=#695f39
palette = 4=#496088
palette = 5=#643c7a
palette = 6=#2a5443
palette = 7=#b6bac3
palette = 8=#484e5b
palette = 9=#8d4c57
palette = 10=#386955
palette = 11=#695f39
palette = 12=#496088
palette = 13=#643c7a
palette = 14=#2a5443
palette = 15=#cacdd3
