background = #080808
foreground = #c9cdd4

cursor-color = #b4c2da
cursor-text = #080808
selection-background = #363f4e
selection-foreground = #dcdfe5
split-divider-color = #14161b

palette = 0=#32363e
palette = 1=#c8939c
palette = 2=#90c1ac
palette = 3=#c6bf9f
palette = 4=#93a6c8
palette = 5=#b89dc8
palette = 6=#95bec6
palette = 7=#babfc9
palette = 8=#606876
palette = 9=#dab4ba
palette = 10=#afd4c5
palette = 11=#dad5be
palette = 12=#b4c2da
palette = 13=#ceb9d9
palette = 14=#b5d3d9
palette = 15=#dcdfe5
