background = #f5f5f5
foreground = #31363f

cursor-color = #384d71
cursor-text = #f5f5f5
selection-background = #d0d6e2
selection-foreground = #1f2229

palette = 0=#31363f
palette = 1=#8d4c57
palette = 2=#386955
palette = 3=#695f39
palette = 4=#496088
palette = 5=#794e92
palette = 6=#3b666e
palette = 7=#abb0ba
palette = 8=#646a78
palette = 9=#763a44
palette = 10=#2a5443
palette = 11=#554c2a
palette = 12=#384d71
palette = 13=#643c7a
palette = 14=#2c525a
palette = 15=#d1d5db
