background = #080808
foreground = #c9cdd4

cursor-color = #b4c2da
cursor-text = #050505
selection-background = #1d1f22
selection-foreground = #c9cdd4
split-divider-color = #14161b

palette = 0=#22262e
palette = 1=#c8939c
palette = 2=#90c1ac
palette = 3=#c6bf9f
palette = 4=#93a6c8
palette = 5=#ceb9d9
palette = 6=#afd4c5
palette = 7=#9ca3b0
palette = 8=#363f4e
palette = 9=#c8939c
palette = 10=#90c1ac
palette = 11=#c6bf9f
palette = 12=#93a6c8
palette = 13=#ceb9d9
palette = 14=#afd4c5
palette = 15=#b3b8c2
