#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
IFS=$'\n\t'

readonly config_dir="${0%/*}/config"

for name in settings rules signals; do
	# shellcheck source=/dev/null
	source "$config_dir/$name.sh"
done
