name: luacheck

on: [push, pull_request]

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          sudo apt update
          sudo apt install luarocks
          sudo luarocks install luacheck

      - name: Lint
        run: luacheck .
