name: vint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  vint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup dependencies
        run: pip install vim-vint

      - name: Run vint linter
        run: vint .vim/
