variables: secret.yml

templates:
  anchors:
    _transmission: &transmission
      host: 192.168.1.10
      port: 9091
      username: kutsan
      password: EkYBoNSd6oIUznucRTfQTFCcxC5WeeDaBImPt6I9CncuY9g8mH

schedules:
  - tasks: '*'
    interval:
      minutes: 30

tasks:
  SEARCH:
    # internal
    priority: 1

    # input
    discover:
      what:
        - next_series_episodes: yes
      from:
        - nyaa:
            category: anime eng
            filter: all
      release_estimations: ignore
      interval: 30 minutes

    # filter
    series:
      - Fairy Tail Final Season:
          from_group: HorribleSubs
          quality: 1080p

    # output
    transmission:
      action: add
      <<: *transmission

    # output
    notify:
      entries:
        message: '*EP{{series_id}}* of *{{series_name}}* has captured by transmission daemon.'
        what: accepted
        via:
          - telegram:
              bot_token: '{? telegram.bot_token ?}'
              parse_mode: markdown
              disable_previews: no
              recipients:
                - username: kutsan

  CLEAN:
    # internal
    priority: 2
    no_entries_ok: yes
    disable:
      - seen
      - seen_info_hash

    # input
    from_transmission:
      only_complete: yes
      <<: *transmission

    # filter
    if:
      - transmission_progress == 100: accept
      - transmission_ratio < 0.1: reject

    # output
    transmission:
      action: remove
      <<: *transmission
