variables: variables.yml

templates:
  anchors:
    _transmission: &transmission
      host: '{? transmission.host ?}'
      port: '{? transmission.port ?}'
      username: '{? transmission.username ?}'
      password: '{? transmission.password ?}'

tasks:
  SEARCH:
    # internal
    priority: 1

    # input
    discover:
      what:
        - next_series_episodes: yes
      from:
        - nyaa:
            category: anime eng
            filter: trusted only
      release_estimations: ignore
      interval: 30 minutes

    # filter
    series:
      - Fairy Tail Final Season:
          from_group: HorribleSubs
          quality: 1080p

    # output
    transmission:
      action: add
      <<: *transmission

    # output
    exec:
      allow_background: yes
      auto_escape: yes
      on_output:
        for_accepted:
          - notify
            --title 'flexget'
            --subtitle '{{series_name}}'
            --message 'EP{{series_id}} has been captured into transmission.'
            &

  CLEAN:
    # internal
    priority: 2
    disable:
      - seen
      - seen_info_hash

    # input
    from_transmission:
      only_complete: yes
      <<: *transmission

    # filter
    if:
      - transmission_progress == 100: accept
      - transmission_ratio < 0.2: reject

    # output
    transmission:
      action: remove
      <<: *transmission
